version: '3'
services:
    mongo:
        image: mongo
        ports:
          - '27017:27017'
        volumes:
          - "./backend-mongodb:/data/db"

    mongoexpress:
        image: mongo-express
        ports:
            - '8081:8081'
        links:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017

    mariadb:
        image: mariadb
        volumes:
            - ./backend-mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: strapi
            MYSQL_USER: strapi
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    strapi:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mariadb
            DATABASE_PORT: 3306
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            DATABASE_SSL: 'false'
        volumes:
            - ./backend-strapi:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mariadb

    # nuxtjs:
    #     image: elfensky/taniatours-nuxt
    #     build:
    #         context: ./frontend-nuxt/
    #         dockerfile: Dockerfile
    #     ports:
    #         - 3000:9000
    #     depends_on:
    #         - strapi
