version: '3'
services:
    # DATABASE
    mariadb:
        image: mariadb
        ports:
            - 3306:3306 #should be removed for production
        volumes:
            - ./backend-mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: strapi
            MYSQL_USER: strapi
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # STRAPI (CONTENT API)
    # strapi:
    #     # container_name: backend-strapi
    #     image: strapi/strapi
    #     environment:
    #         DATABASE_CLIENT: mysql
    #         DATABASE_HOST: mariadb
    #         DATABASE_PORT: 3306
    #         DATABASE_NAME: strapi
    #         DATABASE_USERNAME: strapi
    #         DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    #         DATABASE_SSL: 'false'
    #     volumes:
    #         - ./backend-strapi:/srv/app
    #     ports:
    #         - '1337:1337'
    #     command: npm run strapi install graphql

    #     depends_on:
    #         - mariadb

    # NODEJS+EXPRESS (BOOKING API)
    express:
        image: elfensky/taniatours-node
        build:
            context: ./backend-node/
            dockerfile: ./Dockerfile #remove ./ if it doesn't work
        env_file:
            - ./backend-node/ormconfig.docker.env
        environment:
            NODE_ENV: Production
        ports:
            - 3001:3001
        depends_on:
            - mariadb

    # NUXT FRONTEND
    # nuxt:
    #     image: elfensky/taniatours-nuxt
    #     # network_mode: 'host'
    #     build:
    #         context: ./frontend-nuxt/
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - 3000:3000
    #     depends_on:
    #         - express
