version: '4'
services:
    # switched to firebase for auth, mongo no longer neccesary
    # mongo:
    #     image: mongo
    #     ports:
    #         - '27017:27017' #should be removed for production
    #     volumes:
    #         - './backend-mongodb:/data/db'

    # mongoexpress:
    #     image: mongo-express
    #     ports:
    #         - '8081:8081'
    #     links:
    #         - mongo
    #     environment:
    #         - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017

    mariadb:
        image: mariadb
        ports:
            - 3306:3306 #should be removed for production
        volumes:
            - ./backend-mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: strapi
            MYSQL_USER: strapi
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     depends_on:
    #         - mariadb

    # phpmyadmin:
    #     image: phpmyadmin
    #     restart: always
    #     ports:
    #       - 8080:80
    #     environment:
    #       - PMA_ARBITRARY=1

    strapi:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mariadb
            DATABASE_PORT: 3306
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            DATABASE_SSL: 'false'
        volumes:
            - ./backend-strapi:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mariadb

    # express:
    #     image: elfensky/taniatours-node
    #     build:
    #         context: ./backend-node/
    #         dockerfile: ./Dockerfile  #remove ./ if it doesn't work
    #     environment:
    #         NODE_ENV: production
    #     ports:
    #         - 3001:3001
    #     depends_on:
    #         - strapi

    # nuxt:
    #     image: elfensky/taniatours-nuxt
    #     build:
    #         context: ./frontend-nuxt/
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - 3000:9000
    #     depends_on:
    #         - strapi
