version: '3'
services:
    mariadb:
        image: mariadb
        volumes:
            - ./backend-mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: strapi
            MYSQL_USER: strapi
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    strapi:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mariadb
            DATABASE_PORT: 3306
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            DATABASE_SSL: 'false'
        volumes:
            - ./backend-strapi:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mariadb

    nuxtjs:
        image: elfensky/taniatours-nuxt
        build:
            context: ./frontend-nuxt/
            dockerfile: Dockerfile
        ports:
            - 3000:9000
        depends_on:
            - strapi
